version: "3.8"

networks:
  n8n-network:
    driver: bridge

volumes:
  n8n_data: {} 
  supabase_data: {}

services:
  supabase-db:
    image: docker.io/supabase/postgres:15.8.1.126
    container_name: supabase-db
    restart: unless-stopped
    ports:
      - "54322:5432"
    volumes:
      - supabase_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=supabasepass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=n8n
    networks:
      - n8n-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d n8n"]
      interval: 10s
      timeout: 5s
      retries: 5

  n8n:
    image: docker.n8n.io/n8nio/n8n:1.105.4
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=supabase-db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=supabasepass
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n-network
    depends_on:
      supabase-db:
        condition: service_healthy